name: Build & Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@v0.58.3
      with:
        args: --gc --minify
    - uses: wei/rclone@v1.1.1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: sync ./public dex-s:test
